w04/d02/angie/oceans_app/config/routes.rb
OceansApp::Application.routes.draw do
root :to => 'oceans#index'
  get '/oceans' => 'oceans#index'
  get '/oceans/new' => 'oceans#new'
  post '/oceans' => 'oceans#create'
  get '/oceans/:id' => 'oceans#show', :as => 'ocean'
  get '/oceans/:id/edit' => 'oceans#edit', :as => 'ocean_edit'
  post '/oceans/:id' => 'oceans#update'
  post '/oceans/:id/delete' => 'oceans#destroy', :as => 'ocean_delete'

end

w04/d02/angie/oceans_app/app/models/ocean.rb
class Ocean < ActiveRecord::Base
  attr_accessible :name, :avg_depth
end

w04/d02/angie/oceans_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

w04/d02/angie/oceans_app/app/controllers/oceans_controller.rb
class OceansController < ApplicationController
  def index
    @oceans = Ocean.all
  end

  def show
    @ocean = Ocean.find params[:id]
  end

  def new
  end

  def create
    Ocean.create(params[:ocean])
    redirect_to oceans_path
  end

  def edit
    @ocean = Ocean.find(params[:id])
  end

  def update
    ocean = Ocean.find(params[:id])
    ocean.update_attributes(params[:ocean])
    redirect_to ocean_path(ocean.id)
  end

  def destroy
    ocean = Ocean.find(params[:id])
    ocean.destroy
    redirect_to ocean_path
  end

end

w04/d02/angie/oceans_app/app/helpers/application_helper.rb
module ApplicationHelper
end

w04/d02/angie/oceans_app/app/views/oceans/edit.html.erb
<form method="post" action="<%=ocean_path(@ocean.id)%>">
  <p>Name: <input type="text" name="ocean[name]" value="<%= @ocean.name %>" autofocus></p>
  <p>Average Depth: <input type="text" name="ocean[avg_depth]" value="<%= @ocean.avg_depth %>">
  </p>
  <button>Ocean me prawn!</button>
</form>

w04/d02/angie/oceans_app/app/views/oceans/index.html.erb
<h2>Oceans</h2>
<ul>
  <% @oceans.each do |ocean| %>
    <li><%= link_to ocean.name, ocean_path(ocean) %> has an average depth of <%= number_to_human ocean.avg_depth%>.</li>
  <% end %>
</ul>

w04/d02/angie/oceans_app/app/views/oceans/new.html.erb
<form method="post" action="/oceans">
  <p>Name: <input type="text" name="ocean[name]" autofocus></p>
  <p>Average Depth: <input type="text" name="ocean[avg_depth]"></p>
  <button>Ocean me prawn!</button>
</form>

w04/d02/angie/oceans_app/app/views/oceans/show.html.erb
<h2><%= @ocean.name %></h2>
Average Depth: <%= @ocean.avg_depth %>

<%= link_to 'Edit Ocean', ocean_edit_path(@ocean.id) %>
<%= button_to 'Destroy Ocean', ocean_delete_path(@ocean.id) %>