w04/d03/nick/gallery_app/config/routes.rb
GalleryApp::Application.routes.draw do
  resources :artists, :artworks
end

w04/d03/nick/gallery_app/app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  hometown    :string(255)
#  profile_pic :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Artist < ActiveRecord::Base
  attr_accessible :name, :hometown, :profile_pic
  has_many :artworks
end

w04/d03/nick/gallery_app/app/models/artwork.rb
# == Schema Information
#
# Table name: artworks
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  location   :string(255)
#  info       :string(255)
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null


class Artwork < ActiveRecord::Base
  attr_accessible :title, :location, :info, :image, :artist_id
  belongs_to :artist
end

w04/d03/nick/gallery_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

w04/d03/nick/gallery_app/app/controllers/artists_controller.rb
class ArtistsController  < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find params[:id]
  end

  def new
    @artist = Artist.new
  end

  def create
    artist = Artist.create params[:artist]
    redirect_to artists_path
  end

  def destroy
    artist = Artist.find params[:id]
    artist.destroy
    redirect_to artists_path
  end

  def edit
    @artist = Artist.find params[:id]
  end

  def update
    artist = Artist.find params[:id]
    artist.update_attributes params[:artist]
    redirect_to artist_path(artist)
  end
end

w04/d03/nick/gallery_app/app/controllers/artworks_controller.rb
class ArtworksController  < ApplicationController
  def index
    @artworks = Artwork.all
  end

  def show
    @artwork = Artwork.find params[:id]
  end

  def new
    @artwork = Artwork.new
  end

  def create
    artwork = Artwork.create params[:artwork]
    redirect_to artwork_path(artwork)
  end

  def destroy
    artwork = Artwork.find params[:id]
    artwork.destroy
    redirect_to artworks_path
  end

  def edit
    @artwork = Artwork.find params[:id]
  end

  def update
    artwork = Artwork.find params[:id]
    artwork.update_attributes params[:artwork]
    redirect_to artwork_path(artwork)
  end
end

w04/d03/nick/gallery_app/app/helpers/application_helper.rb
module ApplicationHelper
end

w04/d03/nick/gallery_app/app/views/artworks/_form.html.erb
<%= form_for @artwork do |f| %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :location %>
  <%= f.text_field :location %>
</p>
<p>
  <%= f.label :info %>
  <%= f.text_field :info %>
</p>
<p>
  <%= f.label :image %>
  <%= f.text_field :image %>
</p>


<p>
    <%= f.label :artist_id %>
    <select name="artwork[artist_id]">
    <% Artist.order(:name).each do |artist| %>
    <option value=<%= artist.id%> <%= 'selected' if artist.id == @artwork.artist_id %>><%=artist.name %></option>
      <% end %>
  </p>

  <%= f.submit %>
<% end %>

w04/d03/nick/gallery_app/app/views/artworks/edit.html.erb
<h1>Edit artwork</h1>
<%= render :partial => 'form' %>

w04/d03/nick/gallery_app/app/views/artworks/index.html.erb
<ol>
  <% @artworks.each do |artwork| %>
  <li>
    <ul>
      <li><%= link_to artwork.title, artwork_path(artwork) %></li>
      <li><%= artwork.location %></li>
      <li><%= image_tag artwork.image %></li>
    </ul>
  </li>
<% end %>
</ol>

w04/d03/nick/gallery_app/app/views/artworks/new.html.erb
<h1>New artwork</h1>
<%= render :partial => 'form' %>

w04/d03/nick/gallery_app/app/views/artworks/show.html.erb
<h2><%= @artwork.title %></h2>
<p><%= @artwork.location %></p>
<p><%= @artwork.info %></p>
<%= image_tag @artwork.image %>

<%= link_to 'Edit artwork', edit_artwork_path(@artwork) %>
<%= button_to 'Delete artwork', @artwork, :method => 'delete' %>