w04/d02/riana/mountains_app/config/routes.rb
MountainsApp::Application.routes.draw do
  root :to => 'mountains#home'

  get '/mountains' => 'mountains#home'
  get '/mountains/new' => 'mountains#new'
  post '/mountains' => 'mountains#create'
  get '/mountains/:id' => 'mountains#show', :as => 'mountain'
  post '/mountains/:id' => 'mountains#update'
  get '/mountains/:id/edit' => 'mountains#edit', :as => 'mountain_edit'
  get '/mountains/:id/delete' => 'mountains#delete', :as => 'mountain_delete'
end

w04/d02/riana/mountains_app/app/models/mountain.rb
# == Schema Information
#
# Table name: mountains
#
#  id       :integer          not null, primary key
#  name     :string(255)
#  image    :text
#  height   :integer
#  location :text
#

class Mountain < ActiveRecord::Base
  attr_accessible :name, :image, :height, :location
end

w04/d02/riana/mountains_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

w04/d02/riana/mountains_app/app/controllers/mountains_controller.rb
class MountainsController < ApplicationController
  def home
    @mountains = Mountain.all
  end

  def show
    @mountain = Mountain.find(params[:id])
  end

  def new
  end

  def create
    Mountain.create(params[:mountain])
    redirect_to mountains_path
  end

  def edit
    @mountain = Mountain.find(params[:id])
  end

  def update
    mountain = Mountain.find(params[:id])
    mountain.update_attributes(params[:mountain])
    redirect_to mountains_path
  end

  def delete
    mountain = Mountain.find(params[:id])
    mountain.destroy
    redirect_to mountains_path
  end
end

w04/d02/riana/mountains_app/app/helpers/application_helper.rb
module ApplicationHelper
end

w04/d02/riana/mountains_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Marcellus+SC' rel='stylesheet' type='text/css'>
  <title>MountainsApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <ul>
      <li><%= link_to('Mountains', root_path) %></li>
      <li><%= link_to('New Mountain', mountains_new_path) %></li>
    </ul>
  </nav>

<%= yield %>

</body>
</html>