w04/d03/nick/cookbook_app/config/routes.rb
CookbookApp::Application.routes.draw do
  resources :books, :recipes, :ingredients
end

w04/d03/nick/cookbook_app/app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  cuisine    :string(255)
#  chef       :string(255)
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Book < ActiveRecord::Base
  attr_accessible :title, :cuisine, :chef, :image, :recipe_ids
  has_many :recipes
end

w04/d03/nick/cookbook_app/app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  measurement :string(255)
#  cost        :decimal(, )
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Ingredient < ActiveRecord::Base
  attr_accessible :name, :measurement, :cost, :image
  has_and_belongs_to_many :recipes
end

w04/d03/nick/cookbook_app/app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  course       :string(255)
#  cooktime     :integer
#  servingsize  :integer
#  instructions :text
#  image        :text
#  book_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Recipe < ActiveRecord::Base
  attr_accessible :name, :course, :cooktime, :servingsize, :instructions, :image, :book_id, :ingredient_ids
  belongs_to :book
  has_and_belongs_to_many :ingredients
end

w04/d03/nick/cookbook_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

w04/d03/nick/cookbook_app/app/controllers/books_controller.rb
class BooksController  < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find params[:id]
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.create params[:book]
    redirect_to book_path(book)
  end

  def destroy
    book = Book.find params[:id]
    book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find params[:id]
  end

  def update
    book = Book.find params[:id]
    book.update_attributes params[:book]
    redirect_to book_path(book)
  end
end

w04/d03/nick/cookbook_app/app/controllers/ingredients_controller.rb
class IngredientsController  < ApplicationController
  def index
  @ingredients = Ingredient.all
  end

  def show
  @ingredient = Ingredient.find params[:id]
  end

  def new
  @ingredient = Ingredient.new
  end

  def create
  ingredient = Ingredient.create params[:ingredient]
  redirect_to ingredient_path(ingredient)
  end

  def destroy
  ingredient = Ingredient.find params[:id]
  ingredient.destroy
  redirect_to ingredients_path
  end

  def edit
  @ingredient = Ingredient.find params[:id]
  end

  def update
    ingredient = Ingredient.find params[:id]
    ingredient.update_attributes params[:ingredient]
    redirect_to ingredient_path(ingredient)
  end
end

w04/d03/nick/cookbook_app/app/controllers/recipes_controller.rb
class RecipesController  < ApplicationController
  def index
  @recipes = Recipe.all
  end

  def show
  @recipe = Recipe.find params[:id]
  end

  def new
  @recipe = Recipe.new
  end

  def create
  recipe = Recipe.create params[:recipe]
  redirect_to recipe_path(recipe)
  end

  def destroy
  recipe = Recipe.find params[:id]
  recipe.destroy
  redirect_to recipes_path
  end

  def edit
  @recipe = Recipe.find params[:id]
  end

  def update
    recipe = Recipe.find params[:id]
    recipe.update_attributes params[:recipe]
    redirect_to recipe_path(recipe)
  end
end

w04/d03/nick/cookbook_app/app/helpers/application_helper.rb
module ApplicationHelper
end

w04/d03/nick/cookbook_app/app/views/books/_form.html.erb
<%= form_for @book do |f| %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :cuisine %>
  <%= f.text_field :cuisine %>
</p>
<p>
  <%= f.label :chef %>
  <%= f.text_field :chef %>
</p>
<p>
  <%= f.label :image %>
  <%= f.text_field :image %>
</p>

  <% Recipe.order(:name).each do |recipe| %>
  <p>
  <%= check_box_tag 'book[recipe_ids][]', recipe.id,
                    recipe.in?(@book.recipes) %>
  <%= recipe.name %>
  </p>
  <% end %>

  <%= f.submit %>
<% end %>

w04/d03/nick/cookbook_app/app/views/books/edit.html.erb
<h1>Edit book</h1>
<%= render :partial => 'form' %>

w04/d03/nick/cookbook_app/app/views/books/index.html.erb
<ol>
  <% @books.each do |book| %>
  <li>
    <ul>
      <li><%= link_to book.title, book_path(book.id) %></li>
      <li><%= book.cuisine %></li>
      <li><%= book.chef %></li>
      <li><%= image_tag book.image %></li>
    </ul>
  </li>
<% end %>
</ol>

w04/d03/nick/cookbook_app/app/views/books/new.html.erb
<h1>New book</h1>
<%= render :partial => 'form' %>

w04/d03/nick/cookbook_app/app/views/books/show.html.erb
<h2><%= @book.title %></h2>
<p><%= @book.cuisine %></p>
<p><%= @book.chef %></p>
<%= image_tag @book.image %>

<%= link_to 'Edit book', edit_book_path(@book) %>
<%= button_to 'Delete book', @book, :method => 'delete' %>

<% @book.recipes.each do |recipe| %>
  <h3><%= recipe.name %></h3>
  <%= image_tag recipe.image, :class => 'recipe' %>
  <% recipe.ingredients.each do |ingredient| %>
  <%= ingredient.name %>
  <%= image_tag ingredient.image, :class => 'ingredient' %>
  <% end %>
<% end %>

w04/d03/nick/cookbook_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookbookApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
<ul>
  <li><%= link_to 'Books', books_path %></li>
  <li><%= link_to 'Recipes', recipes_path %></li>
  <li><%= link_to 'Ingredients', ingredients_path %></li>
  <li><%= link_to 'New_Book', new_book_path %></li>
  <li><%= link_to 'New_Recipe', new_recipe_path %></li>
  <li><%= link_to 'New_Ingredient', new_ingredient_path %></li>
</ul>
</nav>

<%= yield %>

</body>
</html>